version: '3.1'

services:
  db.media:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql_media-autoload:/docker-entrypoint-initdb.d:ro
      - ./mysql_media-datadir:/var/lib/mysql:z
      - ./mysql_media-shr:/shr:z
      - ./mysql_media-conf.d:/etc/mysql/conf.d:z
  app:
    image: dina/media_enhanced:v0.2
    environment:
     - VIRTUAL_HOST=beta-media.dina-web.net
     - VIRTUAL_PORT=8080
    volumes:
      - ./srv/media:/opt/data/media
      - ./srv/log:/opt/jboss/wildfly/standalone/log
    links:
      - db.media:dbmedia

networks:
  default:
    external:
      name: proxydocker_default
